name: Copilot API

on:
  push:
    branches:
    - 'main'
    paths:
    - 'copilot/src/**'
    - 'common/src/service/TenantToken/**'
    - '.github/workflows/copilot-api.yml'
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches:
    - 'main'
    paths:
    - 'copilot/src/**'
    - 'common/src/service/TenantToken/**'
    - '.github/workflows/copilot-api.yml'

env:
  RUNNING_IN_PIPELINE: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    uses: norconsult-digital/platform/.github/workflows/dotnet-ci-jobs.yml@main
    with:
      dotnetVersion: '9.*'
      dockerFile: 'copilot/src/Api/Dockerfile'
      repositoryName: 'isy360/copilot-api'
      testProjects: 'copilot/src/**'
      migrationBundleArguments: '--project copilot/src/Api'
      migrationBundleAppSettingsPath: 'copilot/src/Api'

  deploy:
    needs: build
    strategy:
      matrix:
        include:
        - environment: 'yoshi-test'
          environmentName: 'test'
          azureServicePrincipalId: ${{ vars.AZURE_YOSHI_NON_PROD_SERVICE_PRINCIPAL_ID }}
          dbConnection: ${{ vars.COPILOT_TEST_DB_CONNECTION }}
        - environment: 'yoshi-stage'
          environmentName: 'stage'
          azureServicePrincipalId: ${{ vars.AZURE_YOSHI_PROD_SERVICE_PRINCIPAL_ID }}
          dbConnection: ${{ vars.COPILOT_STAGE_DB_CONNECTION }}
        - environment: 'yoshi-prod'
          environmentName: 'prod'
          azureServicePrincipalId: ${{ vars.AZURE_YOSHI_PROD_SERVICE_PRINCIPAL_ID }}
          dbConnection: ${{ vars.COPILOT_PROD_DB_CONNECTION }}
    uses: norconsult-digital/platform/.github/workflows/dotnet-cd-jobs.yml@main
    with:
      environment: ${{ matrix.environment }}
      environmentName: ${{ matrix.environmentName }}
      repositoryName: 'isy360/copilot-api'
      migrationBundleArguments: '--project copilot/src/Api'
      azureServicePrincipalId: ${{ matrix.azureServicePrincipalId }}
      dbConnection: ${{ matrix.dbConnection }}