name: Copilot Api Seeding tools script

on:
    workflow_dispatch:
      inputs:

        action:
          description: 'Action to perform'
          required: true
          type: choice
          options:
            - 'deploy'
            - 'promote-alias'
            - 'delete-index'

        environment:
          description: 'Target environment for the action'
          required: true
          default: 'yoshi-test'
          type: choice
          options:
            - 'yoshi-test'
            - 'yoshi-stage'
            - 'yoshi-prod'

        domain:
          required: true
          description: 'Domain to operate on'
          type: choice
          options:
            - 'konstruksjon'
            - 'svv'
            - 'banenor'
            - 'project-economy'
            - 'isy-road'

        data-version:
          description: "Data version to load. This parameter is required only for the 'deploy' action (e.g., 202401)."
          required: false
          type: string

        index-version:
          description: "Index version to create or delete (for 'deploy' or 'delete' actions, e.g., v2)"
          required: false
          type: string

        target-index-version:
          description: "Index version to promote (for 'promote-alias' action, e.g., v2)"
          required: false
          type: string

        force-delete:
          description: "⚠️ Confirm deletion (for 'delete-index' action)"
          required: false
          type: boolean
          default: false

permissions:
  id-token: write
  contents: read

jobs:
    # Job to deploy a new, versioned index
  deploy:
    if: ${{ github.event.inputs.action == 'deploy' }}
    runs-on: private-ubuntu-runner
    env:
      UV_SYSTEM_PYTHON: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "copilot/ops/seeding/requirements.txt"

      - name: Log in to Azure (Test)
        if: ${{ github.event.inputs.environment == 'yoshi-test' }}
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_YOSHI_NON_PROD_SERVICE_PRINCIPAL_ID }}
          tenant-id: '5546488e-16ae-4971-ba91-b12a928efaf8'
          subscription-id: ${{ vars.ISY360_TEST_SUBSCRIPTION }}

      - name: Log in to Azure (Stage/Prod)
        if: ${{ github.event.inputs.environment == 'yoshi-stage' || github.event.inputs.environment == 'yoshi-prod' }}
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_YOSHI_PROD_SERVICE_PRINCIPAL_ID }}
          tenant-id: '5546488e-16ae-4971-ba91-b12a928efaf8'
          subscription-id: ${{ (github.event.inputs.environment == 'yoshi-stage' && vars.ISY360_STAGE_SUBSCRIPTION) || vars.ISY360_PROD_SUBSCRIPTION }}
      
      - name: Set up Python and Install Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies with uv
        run: uv pip install -r copilot/ops/seeding/requirements.txt

      - name: Run Deploy Action
        run: |
          python copilot/ops/seeding/seeding_tool.py \
            --environment ${{ github.event.inputs.environment }} \
            deploy \
            --domain ${{ github.event.inputs.domain }} \
            ${{ github.event.inputs.data-version && format('--data-version {0}', github.event.inputs.data-version) }} \
            --index-version ${{ github.event.inputs.index-version }}

  # Job to promote an existing index version to the live alias
  promote-alias:
    if: ${{ github.event.inputs.action == 'promote-alias' }}
    runs-on: private-ubuntu-runner
    env:
      UV_SYSTEM_PYTHON: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "copilot/ops/seeding/requirements.txt"

      - name: Log in to Azure (Test)
        if: ${{ github.event.inputs.environment == 'yoshi-test' }}
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_YOSHI_NON_PROD_SERVICE_PRINCIPAL_ID }}
          tenant-id: '5546488e-16ae-4971-ba91-b12a928efaf8'
          subscription-id: ${{ vars.ISY360_TEST_SUBSCRIPTION }}

      - name: Log in to Azure (Stage/Prod)
        if: ${{ github.event.inputs.environment == 'yoshi-stage' || github.event.inputs.environment == 'yoshi-prod' }}
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_YOSHI_PROD_SERVICE_PRINCIPAL_ID }}
          tenant-id: '5546488e-16ae-4971-ba91-b12a928efaf8'
          subscription-id: ${{ (github.event.inputs.environment == 'yoshi-stage' && vars.ISY360_STAGE_SUBSCRIPTION) || vars.ISY360_PROD_SUBSCRIPTION }}

      - name: Set up Python and Install Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies with uv
        run: uv pip install -r copilot/ops/seeding/requirements.txt

      - name: Run Promote Alias Action
        run: |
          python copilot/ops/seeding/seeding_tool.py \
            --environment ${{ github.event.inputs.environment }} \
            promote-alias \
            --domain ${{ github.event.inputs.domain }} \
            --target-index-version ${{ github.event.inputs.target-index-version }}

  delete-index:
    if: ${{ github.event.inputs.action == 'delete-index' }}
    runs-on: private-ubuntu-runner
    env:
      UV_SYSTEM_PYTHON: 1
    steps:
      - uses: actions/checkout@v4
      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "copilot/ops/seeding/requirements.txt"

      - name: Log in to Azure (Test)
        if: ${{ github.event.inputs.environment == 'yoshi-test' }}
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_YOSHI_NON_PROD_SERVICE_PRINCIPAL_ID }}
          tenant-id: '5546488e-16ae-4971-ba91-b12a928efaf8'
          subscription-id: ${{ vars.ISY360_TEST_SUBSCRIPTION }}

      - name: Log in to Azure (Stage/Prod)
        if: ${{ github.event.inputs.environment == 'yoshi-stage' || github.event.inputs.environment == 'yoshi-prod' }}
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_YOSHI_PROD_SERVICE_PRINCIPAL_ID }}
          tenant-id: '5546488e-16ae-4971-ba91-b12a928efaf8'
          subscription-id: ${{ (github.event.inputs.environment == 'yoshi-stage' && vars.ISY360_STAGE_SUBSCRIPTION) || vars.ISY360_PROD_SUBSCRIPTION }}

      - name: Set up Python and Install Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies with uv
        run: uv pip install -r copilot/ops/seeding/requirements.txt

      - name: Run Delete Index Command
        run: |
          python copilot/ops/seeding/seeding_tool.py \
            --environment ${{ github.event.inputs.environment }} \
            delete-index \
            --domain ${{ github.event.inputs.domain }} \
            --index-version ${{ github.event.inputs.index-version }} \
            ${{ github.event.inputs.force-delete && '--force' }}