name: "Check dotnet version .LTS version"

on:
  schedule:
    - cron: "0 9 * * 3"
  workflow_dispatch:
    inputs:
      support:
        description: "The support level to target (STS, LTS, or Preview)."
        required: true
        default: "LTS"

jobs:
  dotnet-version-sweeper:
    uses: norconsult-digital/.github/.github/workflows/dotnet-version-sweeper.yml@main
    with:
      support: ${{ inputs.support || 'LTS'}}
