name: Specification App Locale Upload

on:
  push:
    branches:
      - 'main'  
    paths:
      - 'frontend/src/apps/specification-app/**'
      - '.github/workflows/specification-app-locale-upload.yml'
  workflow_dispatch:

jobs:
  upload:
    uses: norconsult-digital/platform/.github/workflows/poeditor-upload.yml@main
    with:
      path: 'frontend/src'
      outputPath: 'apps/specification-app/src/locale'
      extractCommand: 'nx run specification-app:extract-i18n --no-cloud'
      projectId: ${{ vars.SPECIFICATION_APP_POEDITOR_PROJECT_ID }}
    secrets:
      API_KEY: ${{ secrets.POEDITOR_API_KEY }}
