name: "[Platform] Check Angular build and test"
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 9 * * 3" # Changed from monthly to Wednesday 9 AM UTC
  workflow_dispatch:
    inputs:
      vmImage:
        required: false
        type: string
        default: "ubuntu-latest"
      workspaceDir:
        required: true
        type: string
      disableNxCloud:
        required: false
        type: boolean
        default: false
    secrets:
      NX_CLOUD_CICD:
        required: true

jobs:
  angular-build-and-test:
    uses: norconsult-digital/.github/.github/workflows/angular-build-and-test.yml@main
    with:
      vmImage: ${{ inputs.vmImage || 'ubuntu-latest' }}
      workspaceDir: ${{ inputs.workspaceDir || 'frontend/src' }} 
      disableNxCloud: ${{ inputs.disableNxCloud || false }}
      NX_CLOUD_CICD: ${{ secrets.NX_CLOUD_CICD }}
