name: "[Platform] Check Angular build and test"
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 9 * * 3" # Changed from monthly to Wednesday 9 AM UTC
  workflow_dispatch:
   
jobs:
  angular-build-and-test:
    uses: norconsult-digital/.github/.github/workflows/angular-build-and-test.yml@main
    with:
      vmImage: ubuntu-latest
      workspaceDir: frontend/src
      disableNxCloud: false
    secrets:
      NX_CLOUD_CICD: ${{ secrets.NX_CLOUD_CICD }}
