name: "[APIM] Publish to Non-Prod and Prod"

on:
  # Triggers when artifacts are pushed to main branch
  push:
    branches: [main]
    paths:
      - "apimartifacts/**"

  # Manual trigger
  workflow_dispatch:
    inputs:
      COMMIT_ID_CHOICE:
        description: 'Choose "publish-all-artifacts-in-repo" only when you want to force republishing all artifacts (e.g. after build failure)'
        required: true
        type: choice
        default: "publish-artifacts-in-last-commit"
        options:
          - "publish-artifacts-in-last-commit"
          - "publish-all-artifacts-in-repo"

jobs:
  publish:
    uses: norconsult-digital/.github/.github/workflows/apim-run-publisher.yml@main
    with:
      COMMIT_ID_CHOICE: ${{ github.event.inputs.COMMIT_ID_CHOICE || 'publish-artifacts-in-last-commit' }}
      API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts
      CONFIGURATION_PROD_YML_PATH: configuration.prod.yml
    secrets: inherit
