name: "[Platform] Bicep File What If Workflow "
permissions:
  contents: read
  pull-requests: write

on:
  schedule:
    - cron: "0 9 * * 3" # Changed from monthly to Wednesday 9 AM UTC
  workflow_dispatch:
    inputs:
      vmImage:
        type: string
        required: false
        default: "ubuntu-latest"
      environment:
        required: true
        type: string
      environmentName:
        required: false
        type: string
      allowedBranches:
        required: false
        type: string
      subscription:
        required: true
        type: string
      resourceGroupName:
        required: true
        type: string
      bicepFile:
        required: true
        type: string
      bicepParameterFile:
        required: true
        type: string
      azureServicePrincipalId:
        required: true
        type: string

jobs:
  bicep-what-if-deploy:
    uses: norconsult-digital/.github/.github/workflows/bicep-what-if-deploy.yml@main
    with:
      vmImage: ${{ inputs.vmImage }}
      environment: ${{ inputs.environment }}
      subscription: ${{ inputs.subscription }}
      resourceGroupName: ${{ inputs.resourceGroupName }}
      bicepFile: ${{ inputs.bicepFile }}
      bicepParameterFile: ${{ inputs.bicepParameterFile }}
      azureServicePrincipalId: ${{ inputs.azureServicePrincipalId }}
