name: "[Platform] Bicep File What If Workflow "
permissions:
  contents: read
  pull-requests: write

on:
  schedule:
    - cron: "0 9 * * 3" # Changed from monthly to Wednesday 9 AM UTC
  workflow_dispatch:
    inputs:
      vmImage:
        type: string
        required: false
        default: "ubuntu-latest"
      environment:
        required: true
        type: string
      environmentName:
        required: false
        type: string
      allowedBranches:
        required: false
        type: string
      subscription:
        required: true
        type: string
      resourceGroupName:
        required: true
        type: string
      bicepFile:
        required: true
        type: string
      bicepParameterFile:
        required: true
        type: string
      azureServicePrincipalId:
        required: true
        type: string

jobs:
  bicep-what-if-deploy:
    uses: norconsult-digital/.github/.github/workflows/bicep-what-if-deploy.yml@main
    with:
      vmImage: "ubuntu-latest"
      environment: "test"
      subscription: ${{ vars.ND_PLAYGROUND_SUBSCRIPTION }}
      resourceGroupName: "rg-b2c-poc"
      bicepFile: "b2c-poc/resources/b2c-poc.bicep"
      bicepParameterFile: "b2c-poc/resources/b2cpoc.parameters.test.json"
      azureServicePrincipalId: ${{ vars.PLATFORM_SERVICE_PRINCIPAL_ID }}
