name: "[Platform] Bicep File What If Workflow "
permissions:
  contents: read
  pull-requests: write

on:
  schedule:
    - cron: "0 9 * * 3" # Changed from monthly to Wednesday 9 AM UTC
  workflow_dispatch:
    inputs:
      vmImage:
        type: string
        required: false
        default: "ubuntu-latest"
      environment:
        required: true
        type: string
      environmentName:
        required: false
        type: string
      allowedBranches:
        required: false
        type: string
      subscription:
        required: true
        type: string
      resourceGroupName:
        required: true
        type: string
      bicepFile:
        required: true
        type: string
      bicepParameterFile:
        required: true
        type: string
      azureServicePrincipalId:
        required: true
        type: string

jobs:
  bicep-what-if-deploy:
    runs-on: ${{ inputs.vmImage }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: 'bicep'

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.azureServicePrincipalId }}
          tenant-id: 'YOUR_TENANT_ID'
          subscription-id: ${{ inputs.subscription }}

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ inputs.subscription }}
          resourceGroupName: ${{ inputs.resourceGroupName }}
          template: ${{ inputs.bicepFile }}
          parameters: ${{ inputs.bicepParameterFile }}
          additionalArguments: "--what-if --rollback-on-error"
