name: "[Platform] Deploy Bicep Files"

permissions:
  id-token: write
  contents: read

on:
  schedule:
    - cron: "0 9 * * 3" # Changed from monthly to Wednesday 9 AM UTC
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
      environmentName:
        required: true
        type: string
      allowedBranches:
        required: false
        type: string
        default: '["main"]'
      runWhatIf:
        required: false
        type: boolean
        default: false
      subscription:
        required: true
        type: string
      resourceGroupName:
        required: true
        type: string
      bicepFile:
        required: true
        type: string
      bicepParameterFile:
        required: true
        type: string
      azureServicePrincipalId:
        required: true
        type: string

jobs:
  deploy:
    uses: norconsult-digital/.github/.github/workflows/deploy-bicep-files.yml@main
    with:
      vmImage: "ubuntu-latest"
      environment: ${{ github.event.inputs.environment }}
      environmentName: ${{ github.event.inputs.environmentName }}
      allowedBranches: ${{ github.event.inputs.allowedBranches }}
      runWhatIf: ${{ github.event.inputs.runWhatIf }}
      subscription: ${{ github.event.inputs.subscription }}
      resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
      bicepFile: ${{ github.event.inputs.bicepFile }}
      bicepParameterFile: ${{ github.event.inputs.bicepParameterFile }}
      azureServicePrincipalId: ${{ github.event.inputs.azureServicePrincipalId }}