name: "[Platform] Docker Image Processing and Push"

permissions:
  contents: read
  id-token: write

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 9 * * 3" # Changed from monthly to Wednesday 9 AM UTC
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
      environmentName:
        required: true
        type: string
      artifactName:
        required: false
        type: string
        default: "container-image"
      repositoryName:
        required: true
        type: string
      azureServicePrincipalId:
        required: true
        type: string

jobs:
  docker-tag-and-push:
    uses: ./.github/workflows/docker-image-processing.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      environmentName: ${{ github.event.inputs.environmentName }}
      artifactName: ${{ github.event.inputs.artifactName }}
      repositoryName: ${{ github.event.inputs.repositoryName }}
      azureServicePrincipalId: ${{ github.event.inputs.azureServicePrincipalId }}
    secrets: inherit
