name: "[Platform] Target supported version"

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
    inputs:
      support:
        description: "The support level to target (STS, LTS, or Preview)."
        required: true
        default: "STS"


jobs:
  donet-version-sweeper:
    uses: norconsult-digital/.github/.github/workflows/dotnet-version-sweeper.yml@main
    with:
      support: ${{ inputs.support }}
