name: "Call Migrations Bundle Create Workflow"

permissions:
  contents: read
  id-token: write

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 9 * * 3" # Runs every Wednesday at 9 AM UTC
  workflow_dispatch:
    inputs:
      gitRepo:
        required: false
        type: string
        default: ""
      nugetConfigPath:
        required: false
        type: string
        default: ""
      migrationBundleArguments:
        required: true
        type: string
      migrationBundleAppSettingsPath:
        required: true
        type: string
      dotnetVersion:
        required: false
        type: string
        default: "7.*"

jobs:
  efcore_migrations_bundle_create:
    uses: norconsult-digital/.github/.github/workflows/efcore-migrations-bundle-create.yml@main
    with:
      gitRepo: ${{ github.event.inputs.gitRepo }}
      nugetConfigPath: ${{ github.event.inputs.nugetConfigPath }}
      migrationBundleArguments: ${{ github.event.inputs.migrationBundleArguments }}
      migrationBundleAppSettingsPath: ${{ github.event.inputs.migrationBundleAppSettingsPath }}
      dotnetVersion: ${{ github.event.inputs.dotnetVersion }}
