name: "[Platform] Nuget Publish"

permissions:
  contents: read
  packages: write
  pull-requests: write

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 9 * * 3" # Wednesday 9 AM UTC
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
      environmentName:
        required: true
        type: string
      projectDir:
        required: true
        type: string
      buildConfiguration:
        required: true
        type: string
      deployAllEnvironments:
        required: false
        type: boolean
        default: false
      dotnetVersion:
        required: false
        type: string
        default: "8.*"

jobs:
  call-nuget-publish:
    uses: norconsult-digital/.github/.github/workflows/nuget-publish.yml@main
    with:
      vmImage: "ubuntu-latest"
      environment: ${{ github.event.inputs.environment }}
      environmentName: ${{ github.event.inputs.environmentName }}
      projectDir: ${{ github.event.inputs.projectDir }}
      buildConfiguration: ${{ github.event.inputs.buildConfiguration }}
      deployAllEnvironments: ${{ github.event.inputs.deployAllEnvironments }}
      dotnetVersion: ${{ github.event.inputs.dotnetVersion }}
    secrets:
      ADO_NUGET_PAT: ${{ secrets.ADO_NUGET_PAT }}
      NUGET_GITHUB_PAT: ${{ secrets.NUGET_GITHUB_PAT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
