name: "[Platform] POEditor Upload Workflow"

permissions:
  contents: write

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 9 * * 3"
  workflow_dispatch:
    inputs:
      path:
        required: true
        type: string
      outputPath:
        required: true
        default: "i18n-generated"
        type: string
      outputFileName:
        required: false
        default: "messages.xlf"
        type: string
      extractCommand:
        required: true
        type: string
      nodeVersion:
        required: false
        default: "20.x"
        type: string
      packageManager:
        required: false
        default: "npm"
        type: string
      cacheDependencyPath:
        required: true
        type: string
      pnpmVersion:
        required: false
        default: "latest"
        type: string
      overwrite:
        required: false
        default: true
        type: boolean
      projectId:
        required: true
        type: string

jobs:
  call-poeditor-upload:
    uses: norconsult-digital/.github/workflows/poeditor-upload.yml@main
    with:
      path: 'frontend/src' 
      outputPath: 'i18n-generated' 
      outputFileName: 'messages.xlf' 
      extractCommand: 'npm run extract-i18n' 
      nodeVersion: '20.x'  
      packageManager: 'npm' 
      cacheDependencyPath: 'frontend/package-lock.json'  
      pnpmVersion: 'latest' 
      overwrite: true  
      projectId: 'defaultProjectId'  
    secrets:
      API_KEY: ${{ secrets.API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
