name: "[Platform] POEditor Upload i18next JSON"

permissions:
  contents: write

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 9 * * 3" # Wednesday 9 AM UTC
  workflow_dispatch:
    inputs:
      path:
        required: true
        type: string
      file:
        required: true
        type: string
      projectId:
        required: true
        type: string
      language:
        required: true
        type: string
      extractCommand:
        required: false
        type: string
      overwrite:
        required: false
        type: boolean
        default: true

jobs:
  call-poeditor-upload:
    uses: norconsult-digital/.github/.github/workflows/poeditor-json-upload.yml@main
    with:
      path: ${{ github.event.inputs.path }}
      file: ${{ github.event.inputs.file }}
      projectId: ${{ github.event.inputs.projectId }}
      language: ${{ github.event.inputs.language }}
      extractCommand: ${{ github.event.inputs.extractCommand }}
      overwrite: ${{ github.event.inputs.overwrite }}
    secrets:
      API_KEY: ${{ secrets.API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}