name: "[Platform] POEditor JSON Download"

permissions:
  contents: write

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 9 * * 3" # Wednesday 9 AM UTC
  workflow_dispatch:
    inputs:
      languages:
        required: true
        type: string
      outputPath:
        required: true
        type: string
      projectId:
        required: true
        type: string

jobs:
  poeditor-jsondownload:
    uses: norconsult-digital/.github/.github/workflows/poeditor-json-download.yml@main
    with:
      languages: ${{ github.event.inputs.languages }}
      outputPath: ${{ github.event.inputs.outputPath }}
      projectId: ${{ github.event.inputs.projectId }}
    secrets:
      API_KEY: ${{ secrets.API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
