name: "[Platform] POEditor Upload Workflow"

permissions:
  contents: write

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 9 * * 3"
  workflow_dispatch:
    inputs:
      path:
        required: true
        type: string
      outputPath:
        required: true
        default: "i18n-generated"
        type: string
      outputFileName:
        required: false
        default: "messages.xlf"
        type: string
      extractCommand:
        required: true
        type: string
      nodeVersion:
        required: false
        default: "20.x"
        type: string
      packageManager:
        required: false
        default: "npm"
        type: string
      cacheDependencyPath:
        required: true
        type: string
      pnpmVersion:
        required: false
        default: "latest"
        type: string
      overwrite:
        required: false
        default: true
        type: boolean
      projectId:
        required: true
        type: string

jobs:
  call-poeditor-upload:
    uses: norconsult-digital/.github/.github/workflows/poeditor-upload.yml@main
    with:
      path: ${{ github.event.inputs.path || 'frontend/src'  }}
      outputPath: ${{ github.event.inputs.outputPath || 'i18n-generated'  }}
      outputFileName: ${{ github.event.inputs.outputFileName || 'messages.xlf' }}
      extractCommand: ${{ github.event.inputs.extractCommand  || 'npm run extract-i18n' }}
      nodeVersion: ${{ github.event.inputs.nodeVersion || '20.x'  }}
      packageManager: ${{ github.event.inputs.packageManager  || 'npm' }}
      cacheDependencyPath: ${{ github.event.inputs.cacheDependencyPath || 'package-lock.json'  }}
      pnpmVersion: ${{ github.event.inputs.pnpmVersion || 'latest' }}
      overwrite: ${{ github.event.inputs.overwrite  || true  }}
      projectId: ${{ github.event.inputs.projectId  || 'defaultProjectId'  }}
    secrets:
      API_KEY: ${{ secrets.API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
