name: "[Platform] Publish Bicep Artifact"

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 9 * * 3" # Changed from monthly to Wednesday 9 AM UTC  
  workflow_dispatch:
    inputs:
      bicepFolder:
        required: true
        type: string
      vmImage:
        required: false
        default: ubuntu-latest
        type: string

jobs:
  call-publish-bicep:
    uses: norconsult-digital/.github/.github/workflows/publish-bicep.yml@main
    with:
      bicepFolder: ${{ github.event.inputs.bicepFolder }}
      vmImage: ${{ github.event.inputs.vmImage }}
