name: "[Platform] Publish Bicep Artifact"

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.bicep"
      - "**/*.json"  # For parameter files
  schedule:
    - cron: "0 9 * * 3" # Wednesday 9 AM UTC
  workflow_dispatch:
    inputs:
      bicepFolder:
        description: "Path to the folder containing Bicep files"
        required: true
        type: string
      environmentName:
        description: "Target environment for the deployment (e.g., dev, test, prod)"
        required: false
        type: string
        default: "dev"
      allowedBranches:
        description: "Comma-separated list or JSON array of branches allowed for deployment (e.g., main,release or [\"main\",\"release\"])"
        required: false
        type: string
        default: "main"
      vmImage:
        description: "VM image to use for the runner"
        required: false
        default: ubuntu-latest
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Environment Name
        run: |
          if [[ ! "${{ github.event.inputs.environmentName }}" =~ ^(dev|test|prod)$ ]]; then
            echo "::error::Invalid environment name. Must be one of: dev, test, prod"
            exit 1
          fi

  call-publish-bicep:
    needs: validate-inputs
    uses: norconsult-digital/.github/.github/workflows/publish-bicep-files.yml@main
    with:
      bicepFolder: ${{ github.event.inputs.bicepFolder }}
      environmentName: ${{ github.event.inputs.environmentName }}
      allowedBranches: ${{ github.event.inputs.allowedBranches }}
      vmImage: ${{ github.event.inputs.vmImage }}
