name: "[Platform] Python CI Workflow"

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 9 * * 3" # Changed from monthly to Wednesday 9 AM UTC      
  workflow_dispatch:
    inputs:
      vmImage:
        type: string
        default: "ubuntu-latest"
        required: false
      gitRepo:
        required: false
        type: string
      dockerBuildContext:
        required: false
        type: string
      dockerFile:
        required: false
        type: string
      dockerBuildArguments:
        required: false
        type: string
      repositoryName:
        required: false
        type: string
      pythonVersion:
        required: false
        default: "3.12"
        type: string
      testPaths:
        required: false
        type: string
        description: "Paths to test directories or files"
      projectPath:
        required: false
        type: string
        default: "."
        description: "Path to the Python project directory"

jobs:
  call-python-ci:
    uses: norconsult-digital/.github/.github/workflows/python-ci.yml@main
    with:
      vmImage: ${{ github.event.inputs.vmImage }}
      gitRepo: ${{ github.event.inputs.gitRepo }}
      dockerBuildContext: ${{ github.event.inputs.dockerBuildContext }}
      dockerFile: ${{ github.event.inputs.dockerFile }}
      dockerBuildArguments: ${{ github.event.inputs.dockerBuildArguments }}
      repositoryName: ${{ github.event.inputs.repositoryName }}
      pythonVersion: ${{ github.event.inputs.pythonVersion }}
      testPaths: ${{ github.event.inputs.testPaths }}
      projectPath: ${{ github.event.inputs.projectPath }}
