name: "[Platform] Renovate Version Upgrades"

permissions:
  id-token: write
  contents: read
  pull-requests: write

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 9 * * 3" # Changed from monthly to Wednesday 9 AM UTC    
  workflow_dispatch:
    inputs:
      include_paths:
        required: true
        type: string
      regex_pattern:
        required: true
        type: string
      extra_labels:
        required: false
        type: string
      subscription_id:
        required: false
        type: string
      acr_name:
        required: false
        type: string
      runner:
        required: false
        type: string
        default: "private-ubuntu-runner"

jobs:
  call-renovate:
    uses: ./.github/workflows/renovate-reusable.yml
    with:
      include_paths: ${{ github.event.inputs.include_paths }}
      regex_pattern: ${{ github.event.inputs.regex_pattern }}
      extra_labels: ${{ github.event.inputs.extra_labels }}
      subscription_id: ${{ github.event.inputs.subscription_id }}
      acr_name: ${{ github.event.inputs.acr_name }}
      runner: ${{ github.event.inputs.runner }}
    secrets:
      RENOVATE_APP_ID: ${{ secrets.RENOVATE_APP_ID }}
      RENOVATE_PRIVATE_KEY: ${{ secrets.RENOVATE_PRIVATE_KEY }}
      RENOVATE_WEBHOOK_SECRET: ${{ secrets.RENOVATE_WEBHOOK_SECRET }}