name: Workflow Security Zizmor

on:
  schedule:
    - cron: "0 0 * * *" # Runs every night at 00:00 UTC
  workflow_dispatch:
    inputs:
      workflows-path:
        description: "Path to workflows directory or specific workflow file"
        required: false
        default: ".github/workflows"
        type: string

permissions: {}

jobs:
  zizmor-scan:
    name: Scan GitHub Actions Workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Run zizmor
        run: |
          uvx zizmor --format=sarif "${{ inputs.workflows-path || '.github/workflows' }}" > zizmor-results.sarif
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload zizmor SARIF results
        uses: github/codeql-action/upload-sarif@v4
        if: always() && hashFiles('zizmor-results.sarif') != ''
        with:
          sarif_file: zizmor-results.sarif
          category: zizmor
