name: alz
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/alz/**'
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - 'terraform/alz/**'

jobs:
  deploy:
    uses: ./.github/workflows/template-deploy-terraform.yml
    with:
      path: ./terraform/alz

concurrency:
  group: ${{ github.workflow }}
