name: "[Platform] Bicep File What If Workflow 

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: "dev"
      bicepFile:
        required: true
        default: "./infra/main.bicep"
      bicepParameterFile:
        required: true
        default: "./infra/parameters.json"

  push:
    branches:
      - main
    paths:
      - "infra/**"

  schedule:
    - cron: "0 9 * * 3" 

jobs:
  run-bicep-validation:
    uses: ./.github/workflows/deploy-bicep-what-if-template.yml
    with:
      vmImage: ubuntu-latest
      environment: ${{ github.event.inputs.environment || 'dev' }}
      subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      resourceGroupName: ${{ secrets.AZURE_RG }}
      bicepFile: ${{ github.event.inputs.bicepFile || './infra/main.bicep' }}
      bicepParameterFile: ${{ github.event.inputs.bicepParameterFile || './infra/parameters.json' }}
      azureServicePrincipalId: ${{ secrets.AZURE_CLIENT_ID }}
