name: Deploy Bicep Files Workflow

on:
  workflow_call:
    inputs:
      vmImage:
        description: "Runner image"
        type: string
        required: false
        default: "ubuntu-latest"
      environment:
        description: "Deployment environment"
        required: true
        type: string
      environmentName:
        description: "Optional environment name for GitHub environment protection"
        required: true
        type: string
      allowedBranches:
        description: "Branches allowed to run deployment"
        required: false
        type: string
        default: '["main"]'
      runWhatIf:
        description: "Run a What-If deployment before actual deploy"
        type: boolean
        required: false
        default: false
      subscription:
        description: "Azure Subscription ID"
        required: true
        type: string
      resourceGroupName:
        description: "Azure Resource Group Name"
        required: true
        type: string
      bicepFile:
        description: "Bicep file to deploy"
        required: true
        type: string
      bicepParameterFile:
        description: "Bicep parameter file"
        required: true
        type: string
      azureServicePrincipalId:
        description: "Azure Service Principal ID"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy_bicep:
    runs-on: ${{ inputs.vmImage }}
    if: ${{ contains(fromJSON(inputs.allowedBranches), github.ref_name) || (startsWith(github.ref_name, 'release') && contains(fromJSON(inputs.allowedBranches), 'release')) }}
    environment: ${{ inputs.environmentName }}
    name: Deploy Bicep File
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: "bicep"

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.azureServicePrincipalId }}
          tenant-id: "5546488e-16ae-4971-ba91-b12a928efaf8"
          subscription-id: ${{ inputs.subscription }}

      - name: What-If / Deploy Bicep file
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ inputs.subscription }}
          resourceGroupName: ${{ inputs.resourceGroupName }}
          template: ${{ inputs.bicepFile }}
          parameters: ${{ inputs.bicepParameterFile }}
          additionalArguments: ${{ inputs.runWhatIf && '--what-if --rollback-on-error' || '' }}
          failOnStdErr: true
