name: Docker Image Processing and Push

on:
  workflow_call:
    inputs:
      environment: 
        required: true
        type: string
      environmentName:
        required: true
        type: string
      artifactName:
        required: false
        default: 'container-image'
        type: string
      repositoryName:
        required: true
        type: string
      azureServicePrincipalId:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  docker-tag-and-push:
    runs-on: private-ubuntu-runner
    environment: ${{ inputs.environment }}
    name: Process and Push Docker Image
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifactName }}

      - name: Load Docker image
        run: docker load --input image.tar

      - name: Determine ACR name and ACR subscription based on environment
        id: acr_config
        shell: bash
        run: |
          if [ "${{ inputs.environmentName }}" = "prod" ] || [ "${{ inputs.environmentName }}" = "stage" ]; then
            echo "registry_name=crndsharedprod.azurecr.io" >> $GITHUB_OUTPUT
            echo "subscription=a60c4c2a-c6d9-4940-85e5-bd1fa4a1dfea" >> $GITHUB_OUTPUT
          else
            echo "registry_name=crndsharednonprod.azurecr.io" >> $GITHUB_OUTPUT
            echo "subscription=21eca75c-ed74-4f47-9f51-c0c345a00859" >> $GITHUB_OUTPUT
          fi

      - name: Generate image tag
        id: tag
        shell: bash
        run: |
          echo "value=${{ inputs.environmentName }}-$(date +%s)" >> $GITHUB_OUTPUT

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.azureServicePrincipalId }}
          tenant-id: '5546488e-16ae-4971-ba91-b12a928efaf8'
          subscription-id: ${{ steps.acr_config.outputs.subscription }}

      - name: Log in to the Azure Container Registry
        run: |
          az acr login --name $(echo "${{ steps.acr_config.outputs.registry_name }}" | cut -d'.' -f1)

      - name: Retag Docker image
        run: |
          docker tag ${{ inputs.repositoryName }}:tmp ${{ steps.acr_config.outputs.registry_name }}/${{ inputs.repositoryName }}:${{ steps.tag.outputs.value }}

      - name: Push Docker image to ACR
        run: |
          docker push ${{ steps.acr_config.outputs.registry_name }}/${{ inputs.repositoryName }}:${{ steps.tag.outputs.value }}