name: Load Testing Workflow

on:
  workflow_call:
    inputs:
      subscription:
        required: true
        type: string
      loadTestConfig:
        required: true
        type: string
        description: Load test config file (caller workflow needs to define a matrix if there are more config files to test)
      loadTestName:
        required: true
        type: string
      loadTestResource:
        required: false
        default: "lt-isy360-common"
        type: string
      loadTestResourceGroup:
        required: false
        default: "rg-load-testing"
        type: string
      azureServicePrincipalId:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  load-testing-jobs:
    name: Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@v5

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.azureServicePrincipalId }}
          tenant-id: "5546488e-16ae-4971-ba91-b12a928efaf8"
          subscription-id: ${{ inputs.subscription }}
          auth-type: SERVICE_PRINCIPAL

      - name: "Azure Load Testing: ${{ inputs.loadTestName }}"
        uses: azure/load-testing@v1.1.27
        with:
          loadTestConfigFile: ${{ inputs.loadTestConfig }}
          loadTestResource: ${{ inputs.loadTestResource }}
          resourceGroup: ${{ inputs.loadTestResourceGroup }}

      - name: Ensure results directory exists
        run: mkdir -p loadTest

      - name: Copy Azure Load Test Results
        run: |
          mkdir -p loadTest
          # Replace the path below with where Azure Load Testing writes the results
          if [ -d "${{ github.workspace }}/azure-load-testing-results" ]; then
            cp -r ${{ github.workspace }}/azure-load-testing-results/* loadTest/
          else
            echo "No Azure Load Testing results found, proceeding with empty loadTest folder."
          fi

      - name: List loadTest folder
        run: ls -la loadTest/
     
      - name: "Publish Load Test Results: ${{ inputs.loadTestName }}"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: loadTestResults_${{ inputs.loadTestName }}
          path: loadTest/
