name: nd-runner-images
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/landingzones/nd-runner-images/**'
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - 'terraform/landingzones/nd-runner-images/**'

jobs:
  deploy:
    uses: ./.github/workflows/template-deploy-terraform.yml
    with:
      path: ./terraform/landingzones/nd-runner-images
