name: 'POEditor Upload Workflow'
on:
  workflow_call:
    inputs:
      path:
        description: 'The path to the project directory'
        required: true
        type: string
      outputPath:
        description: 'The output path for the generated files'
        required: true
        default: 'i18n-generated'
        type: string
      extractCommand:
        description: 'The command to extract xlf files'
        required: true
        type: string
      failOnStderr:
        type: boolean
        default: false
      overwrite:
        description: 'Overwrite existing files on upload'
        required: false
        default: true
        type: boolean
      projectId:
         required: true
         type: string
    secrets:
      API_KEY:
        required: true

jobs:
  upload-to-poeditor:
    runs-on: ubuntu-latest
    name: POEDitor Upload
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: npm install and global packages
        run: |
          cd ${{ inputs.path }}
          npm install
          npm install -g @angular/cli nx

      - name: Generate messages xlf files...
        run: |
          cd ${{ inputs.path }}
          ${{ inputs.extractCommand }}
          # Additional command to check for errors if needed

      - name: Upload to POEditor if files are changed
        run: |
          overwriteValue=$(echo "${{ inputs.overwrite }}" | grep -iq "true" && echo "1" || echo "0")
          for file in ${{ inputs.path }}/${{ inputs.outputPath }}/*.xlf; do
            if ! git diff --exit-code -- "${file}"; then
              echo "Differences found, uploading ${file}..."
              sleep 30 # To avoid throttling by POEditor
              curl -X POST https://api.poeditor.com/v2/projects/upload \
                  -F api_token="${{ secrets.API_KEY }}" \
                  -F id="${{ inputs.projectId }}" \
                  -F updating="terms_translations" \
                  -F language="en" \
                  -F overwrite="${overwriteValue}" \
                  -F read_from_source="1" \
                  -F fuzzy_trigger="1" \
                  -F sync_terms="1" \
                  -F file=@"${file}" \
                  -F tags="{\"obsolete\":\"removed-strings\"}"
            else
              echo "No differences found for ${file}."
            fi
          done

      - name: Add changed xlf files, and push
        run: |
          set -e  # Exit on any non-zero exit code from commands within this step
      
          # Configure Git user information
          git config --global user.email "$GITHUB_ACTOR_EMAIL"
          git config --global user.name "$GITHUB_ACTOR - automatic"
      
          # Loop through xlf files and add changed files
          CHANGES_FOUND=false
          FILES="${{ inputs.path }}/${{ inputs.outputPath }}/*.xlf"
          for file in $FILES; do
            if [ -f "$file" ] && ! git diff --quiet -- "$file"; then
              echo "Changes found in $file"
              git add "$file"
              CHANGES_FOUND=true
            else
              echo "No changes in $file"
            fi
          done
      
          # Commit changes if any
          if $CHANGES_FOUND; then
            # Pull before pushing to ensure there's no conflict or missing data
            git pull --no-rebase origin "${GITHUB_REF#refs/heads/}"
            git commit -m "Automatic workflow update xlf files in ${{ inputs.outputPath }}"            
            # Push changes
            git push origin HEAD:"${GITHUB_REF#refs/heads/}"
          else
            echo "No changes to commit."
          fi                