name: Publish Bicep Artifact

on:
  workflow_call:
    inputs:
      bicepFolder:
        description: "Path to the folder containing Bicep files"
        required: true
        type: string
      environmentName:
        description: "Target environment for the deployment"
        type: string
        default: 'dev'
        required: false
      allowedBranches:
        description: "Comma-separated list of branches allowed for deployment"
        type: string
        default: 'main'
        required: false
      vmImage:
        description: "VM image to use for the runner"
        type: string
        default: 'ubuntu-latest'
        required: false

jobs:
  publish-artifact:
    runs-on: ${{ inputs.vmImage }}
    name: Publish Bicep Artifact
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Check Branch
        if: ${{ inputs.allowedBranches != '' }}
        shell: python
        run: |
          import json
          import os
          
          allowed_branches = "${{ inputs.allowedBranches }}"
          current_branch = os.environ["GITHUB_REF"].removeprefix("refs/heads/")
          
          # Try parsing as JSON first
          try:
              branches = json.loads(allowed_branches)
              if isinstance(branches, str):
                  branches = [branches]
          except json.JSONDecodeError:
              # If not JSON, treat as comma-separated list
              branches = [b.strip() for b in allowed_branches.split(',')]
          
          if current_branch not in branches:
              print(f"::error::Current branch {current_branch} is not in the allowed list: {allowed_branches}")
              exit(1)
          
          print(f"Branch {current_branch} is allowed for deployment")

      - name: Set Environment Variables
        run: |
          echo "ENVIRONMENT=${{ inputs.environmentName }}" >> $GITHUB_ENV
          echo "Deploying to environment: ${{ inputs.environmentName }}"

      - name: Publish bicep
        uses: actions/upload-artifact@v4
        with:
          name: bicep-${{ inputs.environmentName }}
          path: ${{ inputs.bicepFolder }}