name: Publish Bicep Artifact

on:
  workflow_call:
    inputs:
      bicepFolder:
        description: "Folder containing Bicep files to publish"
        required: true
        type: string
      vmImage:
        type: string
        default: 'ubuntu-latest'
        required: false
      environmentName:       
        description: "Optional environment name"
        required: false
        type: string
      allowedBranches:       
        description: "Optional allowed branches"
        required: false
        type: string  

jobs:
  publish-artifact:
    runs-on: ${{ inputs.vmImage }}
    name: Publish Bicep Artifact
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Only run on allowed branches
        if: ${{ inputs.allowedBranches && contains(fromJson(inputs.allowedBranches), github.ref_name) }}
        run: echo "Running on allowed branch ${{ github.ref_name }} for environment ${{ inputs.environmentName }}"

      - name: Publish bicep files
        run: |
          echo "Publishing Bicep files from folder: ${{ inputs.bicepFolder }}"
          ls -la ${{ inputs.bicepFolder }}
