name: Publish Bicep Artifact

on:
  workflow_call:
    inputs:
      bicepFolder:
        description: "Folder containing Bicep files to publish"
        required: true
        type: string
      vmImage:
        type: string
        default: 'ubuntu-latest'
        required: false
      environmentName:       
        description: "Optional environment name"
        required: false
        type: string
      allowedBranches:       
        description: "Optional allowed branches"
        required: false
        type: string  

jobs:
  publish-artifact:
    runs-on: ${{ inputs.vmImage }}
    name: Publish Bicep Artifact
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Publish bicep
        uses: actions/upload-artifact@v4
        with:
          name: bicep
          path: ${{ inputs.bicepFolder }}
