# Automatic update helm chart versions in kustomize.yaml files.
# Ref: https://github.com/renovatebot/github-action?tab=readme-ov-file#example-with-github-app

# Debug using Renovate CLI
# LOG_LEVEL=debug RENOVATE_CONFIG_FILE=.github/renovate.json5 renovate --platform=local --require-config=ignored

# Debug using Renovate docker image and ACR token
# docker run --rm \
#   -e LOG_LEVEL=debug \
#   -e RENOVATE_HOST_RULES='[{"hostType":"docker", "matchHost":"crndsharednonprod.azurecr.io", "username":"00000000-0000-0000-0000-000000000000", "password":"'"$(az acr login --name crndsharednonprod.azurecr.io --expose-token | jq -r .accessToken)"'"}]' \
#   -e RENOVATE_INCLUDE_PATHS='["argo-cd/applications/teams/*/*/test/kustomization.yaml"]' \
#   -v $(pwd):/usr/src/app \
#   renovate/renovate \
#   --platform=local

name: Renovate - version upgrades
on:
  workflow_call:
    inputs:
      include_paths:
        required: true
        type: string
      regex_pattern:
        required: true
        type: string
      extra_labels:
        required: false
        type: string
      subscription_id:
        required: false
        type: string
      acr_name:
        required: false
        type: string
      runner:
        required: false
        type: string
        default: "private-ubuntu-runner"
    secrets:
      RENOVATE_APP_ID:
        required: true
      RENOVATE_PRIVATE_KEY:
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  renovate:
    runs-on: ${{ inputs.runner }}
    environment: validate-kustomization
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Ref: https://github.com/actions/create-github-app-token
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}

      - name: Log in with Azure
        uses: azure/login@v2
        if: ${{ inputs.subscription_id != '' }}
        with:
          client-id: 7afd61a6-ea86-467a-8b46-7ebc2d07a52d
          tenant-id: '5546488e-16ae-4971-ba91-b12a928efaf8'
          subscription-id: ${{ inputs.subscription_id }}

      - name: Log in to the Azure Container Registry
        id: acr_token
        if: ${{ inputs.acr_name != '' }}
        run: |
          AZURE_ACCESS_TOKEN=$(az acr login --name ${{ inputs.acr_name }} --expose-token | jq -r '.accessToken')
          echo "AZURE_ACCESS_TOKEN=${AZURE_ACCESS_TOKEN}" >> $GITHUB_OUTPUT

      # Ref: https://github.com/renovatebot/github-action
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.5
        with:
          configurationFile: .github/renovate.json5
          token: '${{ steps.get_token.outputs.token }}'
        env:
          LOG_LEVEL: debug
          RENOVATE_AUTODISCOVER: true
          RENOVATE_PLATFORM: 'github'
          RENOVATE_HOST_RULES: |
            [
              {
                "hostType": "docker",
                "matchHost": "${{ inputs.acr_name }}.azurecr.io",
                "username": "00000000-0000-0000-0000-000000000000",
                "password": "${{ steps.acr_token.outputs.AZURE_ACCESS_TOKEN }}"
              }
            ]
          RENOVATE_INCLUDE_PATHS: ${{ inputs.include_paths }}
          RENOVATE_ADDITIONAL_BRANCH_PREFIX: "${{ inputs.regex_pattern }}/"
          RENOVATE_COMMIT_MESSAGE_SUFFIX: "${{ inputs.regex_pattern }}"
          RENOVATE_ADD_LABELS: ${{ inputs.extra_labels }}
